---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable and start NGINX service
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Deploy nginx configuration from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Deploy index.html page
  copy:
    src: index.html
    dest: "{{ nginx_root }}/index.html"
    owner: www-data
    group: www-data
    mode: '0644'

